languge: python
python:
  -"3.6"

services:
  - postgresql


#install requirements
install:
  - pip install python-coveralls
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database stackoverflow_test;' -U postgres
  - python manage.py db migrate
  - python manage.py db upgrade

script:
  - nosetests --with-coverage --cover-package=api
  - coveralls

after-success:
  - coveralls